name: Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: CRLF
      run: |
        git config --global core.autocrlf true

    - name: SendGrid Action
      uses: mmichailidis/sendgrid-mail-action@v1.0
      with:
        sendgrid-token: ${{ secrets.SENGRID_TOKEN }}
        mail: 'o.pospisilik@gmail.com'

    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md
    
    - name: Run phpstan
      run: composer phpstan
    
    - name: Run phpcs
      run: composer phpcs
